Add files via upload

diff --git a/pdf/pdf-booklet b/pdf/pdf-booklet
--- a/pdf/pdf-booklet
+++ b/pdf/pdf-booklet
@@ -21,20 +21,29 @@
 #   03/11/2015, V3.0 - Add support for LibreOffice & Ms-Office documents
 #   18/10/2017, V3.1 - Correct critical bug (thanks to Igor Kushnir)
 #   01/05/2020, V3.2 - Switch to pdfbook2
+#                      Adaptation for Ubuntu 20.04 LTS 
 # ---------------------------------------------------------
-
-echo "$$ $@" >> "/home/famille/log.txt"
 
 # variable
 TYPE=""
 ERROR=""
 
+# if no argument, display help
+if [ $# -eq 0 ] 
+then
+	echo "Tool to convert a document to a recto/verso booklet"
+	echo "Parameters are :"
+	echo "  --format         Booklet format (A2 A3 A4 A5 Letter Executive Legal)"
+	echo "  --file <file>    File to convert to booklet"
+	exit 1
+fi
+
 # iterate thru parameters
 while test ${#} -gt 0
 do
     case $1 in
-        --format) shift; FORMAT="$1"; shift; ;;
-        --file) shift; ORIGINAL_URI="$1"; shift; ;;
+        "--format") shift; FORMAT="$1"; shift; ;;
+        "--file") shift; ORIGINAL_URI="$1"; shift; ;;
         *) shift; ;;
     esac
 done
@@ -167,13 +176,18 @@ then
 	pdfbook2 --short-edge --signature ${NUMPAGES} "--paper=${TARGET}paper" "${TMP_PDF}"
 
 	# copy booklet to original directory
+	echo "# Copy resulting PDF booklet"
 	gio copy "${TMP_DIR}/${ORIGINAL_NAME}-book.pdf" "${ORIGINAL_DIR}/${ORIGINAL_NAME}-book.pdf"
 
 	) | zenity --width=500 --height=25 --progress --pulsate --auto-close --title "${FORMAT} booklet generation" --window-icon="/usr/share/icons/pdf-booklet.png"
 fi
 
+# -------------------
+#   End of operation
+# -------------------
+
 # display error message
-[ "${ERROR}" != "" ] && zenity --error --text="${ERROR}"
+[ "${ERROR}" != "" ] && zenity --error --width=300 --text="${ERROR}"
 
 # remove temporary directory
 popd
diff --git a/pdf/pdf-compress b/pdf/pdf-compress
--- a/pdf/pdf-compress
+++ b/pdf/pdf-compress
@@ -10,44 +10,90 @@
 #
 # Revision history :
 #   20/04/2020, V1.0 - Creation by N. Bernaerts
+#   01/05/2020, V1.1 - Adaptation for Ubuntu 20.04 LTS 
 # ---------------------------------------------------
 
+# variable
+ERROR=""
+DENSITY=180
+QUALITY=40
+
+# if no argument, display help
+if [ $# -eq 0 ] 
+then
+	echo "Tool to compress scanned PDF files"
+	echo "Parameters are :"
+	echo "  --density        Document density in DPI (default is ${DENSITY})"
+	echo "  --quality        Jpeg image quality (default is ${QUALITY})"
+	echo "  --file <file>    File to compress"
+	exit 1
+fi
+
+# iterate thru parameters
+while test ${#} -gt 0
+do
+    case $1 in
+        "--density") shift; DENSITY="$1"; shift; ;;
+        "--quality") shift; QUALITY="$1"; shift; ;;
+        "--file") shift; ORIGINAL_URI="$1"; shift; ;;
+        *) shift; ;;
+    esac
+done
+
 # check tools availability
-command -v convert >/dev/null 2>&1 || { zenity --error --text="Please install convert [imagemagick]"; exit 1; }
+command -v convert >/dev/null 2>&1 || ERROR="Please install convert [imagemagick]"
 
-# if no file selected, exit
-DOC_URI="$1"
-[ "$DOC_URI" = "" ] && exit 1
+# generate temporary directory
+TMP_DIR=$(mktemp -t -d "pdf-compress-XXXXXXXX")
+pushd "${TMP_DIR}"
 
-# extract document name and extension
-DOC_BASE=$(echo "${DOC_URI}" | sed 's/^\(.*\)\.[a-zA-Z0-9]*$/\1/')
-DOC_EXT=$(echo "${DOC_URI}" | sed 's/^.*\.\([a-zA-Z0-9]*\)$/\1/')
+# check if file is provided
+[ "${ERROR}" = "" -a "${ORIGINAL_URI}" = "" ] && ERROR="No file selected"
 
-# set PDF extension for files without extension
-[ "${DOC_BASE}" = "${DOC_EXT}" ] && DOC_EXT="pdf"
+# generate filename data
+if [ "${ERROR}" = "" ]
+then
+	# generate filenames
+	ORIGINAL_DIR=$(dirname "${ORIGINAL_URI}")
+	ORIGINAL_FILE=$(basename "${ORIGINAL_URI}")
+	ORIGINAL_NAME="${ORIGINAL_FILE%.*}"
 
-# generate temporary files and directory
-TMP_DIR=$(mktemp -t -d "pdf-repair-XXXXXXXX")
-TMP_ORIGINAL="${TMP_DIR}/original.pdf"
-TMP_COMPRESS="${TMP_DIR}/compress.pdf"
+	# generate temporary filenames
+	TMP_ORIGINAL="${TMP_DIR}/original.pdf"
+	TMP_COMPRESS="${TMP_DIR}/compressed.pdf"
+fi
 
-# copy input file to temporary local file
-gio copy "${DOC_URI}" "${TMP_ORIGINAL}"
+# ---------------------------
+#  Compress with Imagemagick
+# ---------------------------
 
-# -----------------------
-# Repair with GhostScript
-# -----------------------
+if [ "${ERROR}" = "" ]
+then
+	(
 
-# generate repaired PDF
-convert -density 180x180 -quality 40 -compress jpeg "${TMP_ORIGINAL}" "${TMP_COMPRESS}"
+	# copy input file to temporary folder
+	echo "# Copy of original PDF document ..."
+	gio copy "${ORIGINAL_URI}" "${TMP_ORIGINAL}"
+	
+	# compress PDF
+	echo "# Compression of document (${DENSITY} DPI and ${QUALITY} quality) ..."
+	convert -density "${DENSITY}x${DENSITY}" -quality "${QUALITY}" -compress jpeg "${TMP_ORIGINAL}" "${TMP_COMPRESS}"
 
-# place corrected file side to original 
-gio copy "${TMP_COMPRESS}" "${DOC_BASE}-compressed.${DOC_EXT}"
+	# copy compressed file side to original 
+	echo "# Copy of compressed PDF ..."
+	gio copy "${TMP_COMPRESS}" "${ORIGINAL_DIR}/${ORIGINAL_NAME}-compressed.pdf"
 
-# ------------
-#   Cleanup
-# ------------
+	) | zenity --width=500 --height=25 --progress --pulsate --auto-close --title "Compress scanned PDF" --window-icon="/usr/share/icons/pdf-compress.png"
+fi
+
+# -------------------
+#   End of operation
+# -------------------
+
+# display error message
+[ "${ERROR}" != "" ] && zenity --error --width=300 --text="${ERROR}"
 
 # remove temporary directory
+popd
 rm -r "${TMP_DIR}"
 
diff --git a/pdf/pdf-repair b/pdf/pdf-repair
--- a/pdf/pdf-repair
+++ b/pdf/pdf-repair
@@ -5,7 +5,6 @@
 # Depends on :
 #   * ghostscript
 #   * mupdf-tools
-#   * gridsite-clients
 #
 # Parameter :
 #   $1 - URI of original PDF
@@ -15,68 +14,93 @@
 #   20/11/2014, V1.1 - Add file selection dialog box
 #   24/01/2015, V1.2 - Check tools availability
 #   24/11/2017, V2.0 - Add MuTool repair method (thank to Willie Wildgrube idea)
+#   01/05/2020, V2.1 - Add method selection with --method
+#                      Adaptation for Ubuntu 20.04 LTS 
 # ---------------------------------------------------
 
+# variable
+ERROR=""
+METHOD="ghostscript"
+
+# if no argument, display help
+if [ $# -eq 0 ] 
+then
+	echo "Tool to repair a PDF document"
+	echo "Parameters are :"
+	echo "  --method <method>    Reparation method (ghostscrit or mutool)"
+	echo "  --file <file>        File to repair"
+	exit 1
+fi
+
+# iterate thru parameters
+while test ${#} -gt 0
+do
+    case $1 in
+        --method) shift; METHOD="$1"; shift; ;;
+        --file) shift; ORIGINAL_URI="$1"; shift; ;;
+        *) shift; ;;
+    esac
+done
+
 # check tools availability
-command -v gvfs-copy >/dev/null 2>&1 || { zenity --error --text="Please install gvfs-copy [gvfs-bin]"; exit 1; }
-command -v notify-send >/dev/null 2>&1 || { zenity --error --text="Please install notify-send [libnotify-bin]"; exit 1; }
 command -v gs >/dev/null 2>&1 || { zenity --error --text="Please install gs [ghostscript]"; exit 1; }
 command -v mutool >/dev/null 2>&1 || { zenity --error --text="Please install mutool [mupdf-tools]"; exit 1; }
-command -v urlencode >/dev/null 2>&1 || { zenity --error --text="Please install urlencode [gridsite-clients]"; exit 1; }
 
-# check if parameter is given, otherwise open dialog box selection
-[ "$1" != "" ] && DOC_URI="$1" || DOC_URI=$(zenity --file-selection --title="Select PDF file to repair")
+# generate temporary directory
+TMP_DIR=$(mktemp -t -d "pdf-compress-XXXXXXXX")
+pushd "${TMP_DIR}"
 
-# if no file selected, exit
-[ "$DOC_URI" = "" ] && exit 1
+# check if file is provided
+[ "${ERROR}" = "" -a "${ORIGINAL_URI}" = "" ] && ERROR="No file selected"
 
-# extract document name and extension
-DOC_BASE=$(echo "${DOC_URI}" | sed 's/^\(.*\)\.[a-zA-Z0-9]*$/\1/')
-DOC_EXT=$(echo "${DOC_URI}" | sed 's/^.*\.\([a-zA-Z0-9]*\)$/\1/')
+# check repair method
+[ "${ERROR}" = "" -a "${METHOD}" != "ghostscript" -a "${METHOD}" != "mutool" ] && ERROR="Unknown repair tool"
 
-# set PDF extension for files without extension
-[ "${DOC_BASE}" = "${DOC_EXT}" ] && DOC_EXT="pdf"
+# generate filename data
+if [ "${ERROR}" = "" ]
+then
+	# generate filenames
+	ORIGINAL_DIR=$(dirname "${ORIGINAL_URI}")
+	ORIGINAL_FILE=$(basename "${ORIGINAL_URI}")
+	ORIGINAL_NAME="${ORIGINAL_FILE%.*}"
 
-# generate temporary local filename
-TMP_ORIGINAL=$(mktemp -t XXXXXXXX.pdf) && rm "${TMP_ORIGINAL}"
-TMP_REPAIRED=$(mktemp -t XXXXXXXX.pdf) && rm "${TMP_REPAIRED}"
+	# generate temporary filenames
+	TMP_ORIGINAL="${TMP_DIR}/original.pdf"
+	TMP_REPAIRED="${TMP_DIR}/repaired.pdf"
+fi
 
-# copy input file to temporary local file
-gvfs-copy "${DOC_URI}" "${TMP_ORIGINAL}"
+# -------------------
+#   Repair document
+# -------------------
 
-# -----------------------
-# Repair with GhostScript
-# -----------------------
+if [ "${ERROR}" = "" ]
+then
+	(
 
-# generate repaired PDF
-gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -sOutputFile="${TMP_REPAIRED}" "${TMP_ORIGINAL}"
+	# copy input file to temporary folder
+	echo "# Copy of original PDF document ..."
+	gio copy "${ORIGINAL_URI}" "${TMP_ORIGINAL}"
+	
+	# repair PDF
+	echo "# Repair original PDF using ${METHOD} ..."
+	[ "${METHOD}" = "ghostscript" ] && gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -sOutputFile="${TMP_REPAIRED}" "${TMP_ORIGINAL}" \
+	                                || mutool clean "${TMP_ORIGINAL}" "${TMP_REPAIRED}"
 
-# place corrected file side to original 
-gvfs-copy "${TMP_REPAIRED}" "${DOC_BASE} (GhostScript repaired).${DOC_EXT}"
+	# place corrected file side to original 
+	echo "# Copy of repaired PDF ..."
+	gio copy "${TMP_REPAIRED}" "${ORIGINAL_DIR}/${ORIGINAL_NAME}-repaired.pdf"
 
-# remove temporary file
-rm -f "${TMP_REPAIRED}" 
+	) | zenity --width=500 --height=25 --progress --pulsate --auto-close --title "Repair PDF" --window-icon="/usr/share/icons/pdf-repair.png"
+fi
 
-# ------------------
-# Repair with MuTool
-# ------------------
+# -------------------
+#   End of operation
+# -------------------
 
-# generate repaired PDF
-mutool clean "${TMP_ORIGINAL}" "${TMP_REPAIRED}"
+# display error message
+[ "${ERROR}" != "" ] && zenity --error --width=300 --text="${ERROR}"
 
-# place corrected file side to original 
-gvfs-copy "${TMP_REPAIRED}" "${DOC_BASE} (MuPDF repaired).${DOC_EXT}"
+# remove temporary directory
+popd
+rm -r "${TMP_DIR}"
 
-# ------------
-# Notification
-# ------------
-
-# get document name and convert URI format
-DOC_NAME=$(basename "${DOC_URI}")
-DOC_DISPLAY=$(urlencode -d "${DOC_NAME}")
-
-# send desktop notification
-notify-send -i pdf-repair "${DOC_DISPLAY} repaired"
-
-# remove temporary files
-rm -f "${TMP_ORIGINAL}" "${TMP_REPAIRED}"
