Update sshfs-mount

diff --git a/sshfs/sshfs-mount b/sshfs/sshfs-mount
--- a/sshfs/sshfs-mount
+++ b/sshfs/sshfs-mount
@@ -7,8 +7,9 @@
 SSHFS_NAME="$1"
 
 # configuration file
+[ "${SSHFS_NAME}" = "" ] && { zenity --error --text="Resource name parameter missing"; exit 1; }
 SSHFS_CONFIG="$HOME/.config/sshfs-${SSHFS_NAME}.conf"
-[ -f "${SSHFS_CONFIG}" ] || { zenity --error --text="${SSHFS_CONFIG} doesn't exist"; exit 1; }
+[ ! -f "${SSHFS_CONFIG}" ] && { zenity --error --text="${SSHFS_CONFIG} doesn't exist"; exit 1; }
 
 # check tools availability
 command -v nmap >/dev/null 2>&1 || { zenity --error --text="Please install nmap"; exit 1; }
@@ -34,10 +35,9 @@ USER_GID=$(id -g)
 MOUNT_POINT="$HOME/${MOUNT_POINT}"
 [ ! -d "${MOUNT_POINT}" ] && mkdir --parents "${MOUNT_POINT}"
 
-# loop initialisation
+# loop to mount ressource
 INDEX=1
 SERVER_INDEX=0
-# loop to mount ressource
 while [ ${INDEX} -gt 0 -a ${SERVER_INDEX} -eq 0 ]
 do
 	# read server config
@@ -49,9 +49,11 @@ do
 	# if server address is defined, test server
 	if [ "${SERVER_ADDRESS}" != "" ]
 	then
-		# test server
-		echo "${SERVER_INDEX}5"
-		echo "# Checking ${SERVER_LABEL} connectivity ..."
+		# display
+		echo "${INDEX}5"
+		echo "# ${SERVER_LABEL} - Checking connectivity ..."
+
+		# ping server
 		ping -c 1 -W 1 ${SERVER_ADDRESS}
 		SERVER_REACHED=$(nmap --max-retries 1 --host-timeout 5 -p${SERVER_PORT} "${SERVER_ADDRESS}" | grep "open")
 		[ "${SERVER_PROTOCOL}" != "" ] && SERVER_REACHED=$(echo "${SERVER_REACHED}" | grep "${SERVER_PROTOCOL}")
@@ -59,9 +61,17 @@ do
 		# if server reached, end of quest
 		if [ "${SERVER_REACHED}" != "" ]
 		then
+			# display
+			echo "${INDEX}8"
+			echo "# ${SERVER_LABEL} - Reachable"
 			SERVER_INDEX=${INDEX}
 			INDEX=0
+
+		# else try next server
 		else
+			# display
+			echo "${INDEX}8"
+			echo "# ${SERVER_LABEL} - Not reachable"
 			INDEX=$((INDEX + 1))
 		fi
 	# else
@@ -76,12 +86,12 @@ if [ ${SERVER_INDEX} -gt 0 ]
 then
 	# unmount ressource if any
 	echo "50"
-	echo "# Preparation of ${MOUNT_POINT} ..."
+	echo "# ${SERVER_LABEL} - Preparation of ${MOUNT_POINT} ..."
 	fusermount -uz "${MOUNT_POINT}"
 
 	# mount ressource
 	echo "60"
-	echo "# Connection thru ${SERVER_LABEL} ..."
+	echo "# ${SERVER_LABEL} - Connection ..."
 	sshfs -o "reconnect,uid=${USER_UID},gid=${USER_GID}" "${SSHFS_NAME}_${SERVER_INDEX}:" "${MOUNT_POINT}"
 
 	# check ressource
@@ -93,7 +103,7 @@ if [ ${SERVER_INDEX} -gt 0 ]
 then
 	# open file manager windows on the drive
 	echo "80"
-	echo "# Launch file manager ..."
+	echo "# ${SERVER_LABEL} - Launch file manager ..."
 	${FILE_MANAGER} "${MOUNT_POINT}" &
 
 	# sucess notification
