Update mozilla-extension-manager

diff --git a/mozilla/mozilla-extension-manager b/mozilla/mozilla-extension-manager
--- a/mozilla/mozilla-extension-manager
+++ b/mozilla/mozilla-extension-manager
@@ -20,14 +20,15 @@
 #                     Add install/remove
 #                     Add global/per-user
 #  28/12/2016, V2.1 - Add Fedora compatibility thanks to Cedric Brandenbourger
+#  07/02/2017  V2.2 - Remove zenity, as running zenity under root with wayland/mir is not working
 # -------------------------------------------------------
 
 # -------------------------------------------------------
 #   Check tools availability
 # -------------------------------------------------------
 
-command -v unzip >/dev/null 2>&1 || { zenity --error --text="Please install unzip"; exit 1; }
-command -v wget >/dev/null 2>&1 || { zenity --error --text="Please install wget"; exit 1; }
+command -v unzip >/dev/null 2>&1 || { echo "Please install unzip"; exit 1; }
+command -v wget >/dev/null 2>&1 || { echo "Please install wget"; exit 1; }
 
 # ------------------------------------------------------
 #   Constants
@@ -130,7 +131,7 @@ then
   
 # none, error 
 else
-  zenity --error --text="Given parameter is neither a firefox nor a thunderbird extension"
+  echo "Given parameter is neither a firefox nor a thunderbird extension"
   exit 1
 fi
 
@@ -152,7 +153,7 @@ else
   PROFILE_PATH=$(grep "Path=" ${PROFILE_INI} | head -n 1 | cut -d'=' -f2)
   
   # set user profile path or exit if it doesn't exist
-  [ "${PROFILE_PATH}" != "" ] && EXT_PATH="${PATH_USER}/${PROFILE_PATH}/extensions" || { zenity --error --text="User profile doesn't exist"; exit 1; }
+  [ "${PROFILE_PATH}" != "" ] && EXT_PATH="${PATH_USER}/${PROFILE_PATH}/extensions" || { echo "User profile doesn't exist"; exit 1; }
 fi   
 
 # -------------------------------------------------------
@@ -167,13 +168,13 @@ wget -O addon.xpi "${EXT_URL}"
 EXT_UID=$(unzip -p addon.xpi install.rdf | grep "<em:id>" | head -n 1 | sed 's/^.*>\(.*\)<.*$/\1/g')
 
 # if .xpi file could not be read, exit
-[ "${EXT_UID}" = "" ] && { zenity --error --text="Could not retrieve extension file from server"; exit 1; }
+[ "${EXT_UID}" = "" ] && { echo "Could not retrieve extension file from server"; exit 1; }
 
 # action : installation
 if [ "${EXT_ACTION}" = "install" ]
 then
   # check if extension not already installed
-  [ -d "${EXT_PATH}/${EXT_UID}" ] && { zenity --error --text="${EXT_TYPE} extension ${EXT_UID} is already installed"; exit 1; }
+  [ -d "${EXT_PATH}/${EXT_UID}" ] && { echo "${EXT_TYPE} extension ${EXT_UID} is already installed"; exit 1; }
 
   # installation of global extension
   if [ "${EXT_TYPE}" = "global" ]
@@ -199,7 +200,7 @@ then
 # action : removal
 else
   # check if extension is installed
-  [ -d "${EXT_PATH}/${EXT_UID}" ] || { zenity --error --text="${EXT_TYPE} extension ${EXT_UID} was not installed"; exit 1; }
+  [ -d "${EXT_PATH}/${EXT_UID}" ] || { echo "${EXT_TYPE} extension ${EXT_UID} was not installed"; exit 1; }
 
   # removal of a global extension
   if [ "${EXT_TYPE}" = "global" ]
