V3.2 - Handle gio and gvfs-copy tools

diff --git a/thumbnailer/msoffice/msoffice-thumbnailer b/thumbnailer/msoffice/msoffice-thumbnailer
--- a/thumbnailer/msoffice/msoffice-thumbnailer
+++ b/thumbnailer/msoffice/msoffice-thumbnailer
@@ -19,16 +19,22 @@
 # 31/07/2015, V2.1 - More robust unoconv command line (thanks to Vaderqk)
 # 07/10/2017, V2.2 - Speedup with netpbm tools
 # 10/03/2018, V3.0 - Switch from unoconv to libreoffice in headless mode
-# 15/03/2018, V3.1 - Handle libreoffice and soffice binaries
+# 06/11/2018, V3.1 - Handle libreoffice and soffice binaries
+# 08/11/2018, V3.2 - Handle gio and gvfs-copy tools
 # ---------------------------------------------------
 
-# check libreoffice availability (binary can be either libreoffice or soffice)
+# check libreoffice availability
 CMD_OFFICE="libreoffice"
 command -v "${CMD_OFFICE}" >/dev/null 2>&1 || CMD_OFFICE="soffice"
 command -v "${CMD_OFFICE}" >/dev/null 2>&1 || { echo "[error] libreoffice missing"; exit 1; }
 
+# check gio availability
+CMD_COPY="gio"
+command -v "${CMD_COPY}" >/dev/null 2>&1 || CMD_COPY="gvfs-copy"
+command -v "${CMD_COPY}" >/dev/null 2>&1 || { echo "[error] gio or gvfs-copy missing"; exit 1; }
+
 # check tools availability
-command -v gvfs-copy >/dev/null 2>&1 || { echo "[error] gvfs-copy missing"; exit 1; }
+command -v mimetype >/dev/null 2>&1 || { echo "[error] mimetype missing"; exit 1; }
 command -v pbmmake >/dev/null 2>&1 || { echo "[error] pbmmake missing"; exit 1; }
 command -v pngtopnm >/dev/null 2>&1 || { echo "[error] pngtopnm missing"; exit 1; }
 command -v pnmscalefixed >/dev/null 2>&1 || { echo "[error] pnmscalefixed missing"; exit 1; }
@@ -61,12 +67,17 @@ PATH_CACHE="$HOME/.cache/${SCRIPT_NAME}"
 URI_TYPE="${FILE_URI:0:4}"
 if [ "${URI_TYPE}" = "file" ]
 then
-	# convert URI to local path and extract local path
+	# convert URI to local path
 	FILE_PATH=$(printf '%b' "${FILE_URI//%/\\x}")
+
+	# extract local path
 	FILE_LOCAL="${FILE_PATH:7}"
 else
+	# check gvfs-copy availability
+	command -v gvfs-copy >/dev/null 2>&1 || exit 1
+
 	# copy input file to temporary local file
-	gvfs-copy "${FILE_URI}" "${TMP_LOCAL}"
+	[ "${CMD_COPY}" = "gio" ] && "${CMD_COPY}" copy "${FILE_URI}" "${TMP_LOCAL}" || "${CMD_COPY}" "${FILE_URI}" "${TMP_LOCAL}"
 	FILE_LOCAL="${TMP_LOCAL}"	
 fi
 
@@ -109,7 +120,7 @@ DOC_ALPHA="${PATH_CACHE}/${LIBREOFFICE_TYPE}-alpha.pnm"
 [ ! -f "${DOC_ALPHA}" ] && pngtopnm -alpha "${PATH_SYSTEM}/msoffice-${LIBREOFFICE_TYPE}.png" > "${DOC_ALPHA}"
 
 # convert first page to PNG
-${CMD_OFFICE} "-env:UserInstallation=file://${TMP_DIR}" --headless --convert-to png --outdir "${TMP_DIR}" "${FILE_LOCAL}"
+"${CMD_OFFICE}" "-env:UserInstallation=file://${TMP_DIR}" --headless --convert-to png --outdir "${TMP_DIR}" "${FILE_LOCAL}"
 
 # convert PNG to PNM
 FILE_NAME=$(basename "${FILE_LOCAL}")
