V2.4 : Add option to force latest version

diff --git a/ubuntugnome/gnomeshell-extension-manage b/ubuntugnome/gnomeshell-extension-manage
--- a/ubuntugnome/gnomeshell-extension-manage
+++ b/ubuntugnome/gnomeshell-extension-manage
@@ -13,6 +13,7 @@
 #   09/08/2016 - V2.1 : Handle exact or previously available version installation (idea from eddy-geek)
 #   09/09/2016 - V2.2 : Switch to gnome-shell to get version [UbuntuGnome 16.04] (thanks to edgard)
 #   05/11/2016 - V2.3 : Trim Gnome version and add Fedora compatibility (thanks to Cedric Brandenbourger)
+#   19/01/2018 - V2.4 : Add option to force latest version (idea from Yasir Atabani)
 # -------------------------------------------
 
 # check tools availability
@@ -28,7 +29,8 @@ USER_PATH="$HOME/.local/share/gnome-shell/extensions"
 GNOME_SITE="https://extensions.gnome.org"
 
 # get current gnome version (major and minor only)
-GNOME_VERSION="$(DISPLAY=":0" gnome-shell --version | tr -cd "0-9." | cut -d'.' -f1,2)"
+TARGET_VERSION="$(DISPLAY=":0" gnome-shell --version | tr -cd "0-9." | cut -d'.' -f1,2)"
+CURRENT_VERSION="${TARGET_VERSION}"
 
 # default installation path for default mode (user mode, no need of sudo)
 INSTALL_MODE="user"
@@ -38,30 +40,31 @@ INSTALL_SUDO=""
 # help message if no parameter
 if [ ${#} -eq 0 ];
 then
-    echo "Install/remove extension from Gnome Shell Extensions site https://extensions.gnome.org/"
-    echo "Extension ID should be retrieved from https://extensions.gnome.org/extension/<ID>/extension-name/"
-    echo "Parameters are :"
-    echo "  --install               Install extension (default)"
-    echo "  --remove                Remove extension"
-    echo "  --user                  Installation/remove in user mode (default)"
-    echo "  --system                Installation/remove in system mode"
-    echo "  --version <version>     Gnome version (system detected by default)"
-    echo "  --extension-id <id>     Extension ID in Gnome Shell Extension site (compulsory)"
-    exit 1
+	echo "Install/remove extension from Gnome Shell Extensions site https://extensions.gnome.org/"
+	echo "Extension ID should be retrieved from https://extensions.gnome.org/extension/<ID>/extension-name/"
+	echo "Version installed will be targeted as the same as Gnome Shell or the next available one"
+	echo "Parameters are :"
+	echo "  --install               Install extension (default)"
+	echo "  --remove                Remove extension"
+	echo "  --user                  Installation/remove in user mode (default)"
+	echo "  --system                Installation/remove in system mode"
+	echo "  --version <version>     Force Gnome version (use 'latest' to force latest one)"
+	echo "  --extension-id <id>     Extension ID in Gnome Shell Extension site (compulsory)"
+	exit 1
 fi
 
 # iterate thru parameters
 while test ${#} -gt 0
 do
-  case $1 in
-    --install) ACTION="install"; shift; ;;
-    --remove) ACTION="remove"; shift; ;;
-    --user) INSTALL_MODE="user"; shift; ;;
-    --system) INSTALL_MODE="system"; shift; ;;
-    --version) shift; GNOME_VERSION="$1"; shift; ;;
-    --extension-id) shift; EXTENSION_ID="$1"; shift; ;;
-    *) echo "Unknown parameter $1"; shift; ;;
-  esac
+	case $1 in
+		--install) ACTION="install"; shift; ;;
+		--remove) ACTION="remove"; shift; ;;
+		--user) INSTALL_MODE="user"; shift; ;;
+		--system) INSTALL_MODE="system"; shift; ;;
+		--version) shift; TARGET_VERSION="$1"; shift; ;;
+		--extension-id) shift; EXTENSION_ID="$1"; shift; ;;
+		*) echo "Unknown parameter $1"; shift; ;;
+	esac
 done
 
 # if no extension id, exit
@@ -74,10 +77,9 @@ done
 [ "${INSTALL_MODE}" = "system" ] && { EXTENSION_PATH="${SYSTEM_PATH}"; INSTALL_SUDO="sudo"; }
 
 # create temporary files
-TMP_DESC=$(mktemp -t ext-XXXXXXXX.txt)
-TMP_ZIP=$(mktemp -t ext-XXXXXXXX.zip)
-TMP_VERSION=$(mktemp -t ext-XXXXXXXX.ver)
-rm ${TMP_DESC} ${TMP_ZIP}
+TMP_DESC=$(mktemp -t ext-XXXXXXXX.txt) && rm ${TMP_DESC}
+TMP_ZIP=$(mktemp -t ext-XXXXXXXX.zip) && rm ${TMP_ZIP}
+TMP_VERSION=$(mktemp -t ext-XXXXXXXX.ver) && rm ${TMP_VERSION}
 
 # get extension description
 wget --quiet --header='Accept-Encoding:none' -O "${TMP_DESC}" "${GNOME_SITE}/extension-info/?pk=${EXTENSION_ID}"
@@ -92,75 +94,91 @@ EXTENSION_DESCR=$(sed 's/^.*description[\": ]*\([^\"]*\).*$/\1/' "${TMP_DESC}")
 EXTENSION_UUID=$(sed 's/^.*uuid[\": ]*\([^\"]*\).*$/\1/' "${TMP_DESC}")
 
 # if ID not known
-if [ ! -s "${TMP_DESC}" ];
+if [ ! -s "${TMP_DESC}" ]
 then
-  echo "Extension with ID ${EXTENSION_ID} is not available from Gnome Shell Extension site."
+	# error message
+	echo "[Error] Extension with ID ${EXTENSION_ID} is not available from Gnome Shell Extension site."
 
 # else, if installation mode
 elif [ "${ACTION}" = "install" ];
 then
 
-  # extract all available versions
-  sed "s/\([0-9]*\.[0-9]*[0-9\.]*\)/\n\1/g" "${TMP_DESC}" | grep "pk" | grep "version" | sed "s/^\([0-9\.]*\).*$/\1/" > "${TMP_VERSION}"
+	# extract all available versions
+	sed "s/\([0-9]*\.[0-9]*[0-9\.]*\)/\n\1/g" "${TMP_DESC}" | grep "pk" | grep "version" | sed "s/^\([0-9\.]*\).*$/\1/" | sort -V > "${TMP_VERSION}"
 
-  # check if current version is available
-  VERSION_AVAILABLE=$(grep "^${GNOME_VERSION}$" "${TMP_VERSION}")
+	# lok for latest version or for current one
+	[ "${TARGET_VERSION}" = "latest" ] && VERSION_AVAILABLE=$(cat "${TMP_VERSION}" | tail -n 1) || VERSION_AVAILABLE=$(grep "^${TARGET_VERSION}$" "${TMP_VERSION}")
 
-  # if version is not available, get the next one available
-  if [ "${VERSION_AVAILABLE}" = "" ]
-  then
-    echo "${GNOME_VERSION}" >> "${TMP_VERSION}"
-    VERSION_AVAILABLE=$(cat "${TMP_VERSION}" | sort -V | sed "1,/${GNOME_VERSION}/d" | head -n 1)
-  fi
+	# if no candidate version found, get the next one after current version
+	if [ "${VERSION_AVAILABLE}" = "" ]
+	then
+		# create a version list including current version
+		cp "${TMP_VERSION}" "${TMP_DESC}" 
+		echo "${TARGET_VERSION}" >> "${TMP_DESC}"
 
-  # if still no version is available, error message
-  if [ "${VERSION_AVAILABLE}" = "" ]
-  then
-    echo "Gnome Shell version is ${GNOME_VERSION}."
-    echo "Extension ${EXTENSION_NAME} is not available for this version."
-    echo "Available versions are :"
-    sed "s/\([0-9]*\.[0-9]*[0-9\.]*\)/\n\1/g" "${TMP_DESC}" | grep "pk" | grep "version" | sed "s/^\([0-9\.]*\).*$/\1/" | sort -V | xargs
+		# sort by version and get next version available after current version
+		VERSION_AVAILABLE=$(cat "${TMP_DESC}" | sort -V | sed "1,/${TARGET_VERSION}/d" | head -n 1)
+	fi
 
-  # else, install extension
-  else
-    # get extension description
-    wget --quiet --header='Accept-Encoding:none' -O "${TMP_DESC}" "${GNOME_SITE}/extension-info/?pk=${EXTENSION_ID}&shell_version=${VERSION_AVAILABLE}"
+	# if candidate version has been found, installation
+	if [ "${VERSION_AVAILABLE}" != "" ]
+	then
 
-    # get extension download URL
-    EXTENSION_URL=$(sed 's/^.*download_url[\": ]*\([^\"]*\).*$/\1/' "${TMP_DESC}")
+		# get extension description
+		wget --quiet --header='Accept-Encoding:none' -O "${TMP_DESC}" "${GNOME_SITE}/extension-info/?pk=${EXTENSION_ID}&shell_version=${VERSION_AVAILABLE}"
 
-    # download extension archive
-    wget --quiet --header='Accept-Encoding:none' -O "${TMP_ZIP}" "${GNOME_SITE}${EXTENSION_URL}"
+		# get extension download URL
+		EXTENSION_URL=$(sed 's/^.*download_url[\": ]*\([^\"]*\).*$/\1/' "${TMP_DESC}")
 
-    # unzip extension to installation folder
-    ${INSTALL_SUDO} mkdir -p ${EXTENSION_PATH}/${EXTENSION_UUID}
-    ${INSTALL_SUDO} unzip -oq "${TMP_ZIP}" -d ${EXTENSION_PATH}/${EXTENSION_UUID}
-    ${INSTALL_SUDO} chmod +r ${EXTENSION_PATH}/${EXTENSION_UUID}/*
+		# download extension archive
+		wget --quiet --header='Accept-Encoding:none' -O "${TMP_ZIP}" "${GNOME_SITE}${EXTENSION_URL}"
 
-    # list enabled extensions (remove @as in case of no extension enabled)
-    EXTENSION_LIST=$(gsettings get org.gnome.shell enabled-extensions | sed 's/^@as //' | tr -d '[]')
-    [ "${EXTENSION_LIST}" != "" ] && EXTENSION_LIST="${EXTENSION_LIST},"
+		# unzip extension to installation folder
+		${INSTALL_SUDO} mkdir -p ${EXTENSION_PATH}/${EXTENSION_UUID}
+		${INSTALL_SUDO} unzip -oq "${TMP_ZIP}" -d ${EXTENSION_PATH}/${EXTENSION_UUID}
+		${INSTALL_SUDO} chmod +r ${EXTENSION_PATH}/${EXTENSION_UUID}/*
 
-    # if extension not already enabled, declare it
-    EXTENSION_ENABLED=$(echo ${EXTENSION_LIST} | grep ${EXTENSION_UUID})
-    [ "$EXTENSION_ENABLED" = "" ] && gsettings set org.gnome.shell enabled-extensions "[${EXTENSION_LIST}'${EXTENSION_UUID}']"
+		# list enabled extensions (remove @as in case of no extension enabled)
+		EXTENSION_LIST=$(gsettings get org.gnome.shell enabled-extensions | sed 's/^@as //' | tr -d '[]')
+		[ "${EXTENSION_LIST}" != "" ] && EXTENSION_LIST="${EXTENSION_LIST},"
 
-    # success message
-    echo "Gnome Shell version is ${GNOME_VERSION}."
-    echo "Extension ${EXTENSION_NAME} version ${VERSION_AVAILABLE} has been installed in ${INSTALL_MODE} mode (Id ${EXTENSION_ID}, Uuid ${EXTENSION_UUID})"
-    echo "Restart Gnome Shell to take effect."
+		# if extension not already enabled, declare it
+		EXTENSION_ENABLED=$(echo ${EXTENSION_LIST} | grep ${EXTENSION_UUID})
+		[ "$EXTENSION_ENABLED" = "" ] && gsettings set org.gnome.shell enabled-extensions "[${EXTENSION_LIST}'${EXTENSION_UUID}']"
 
-  fi
+		# success message
+		echo "[success] Extension ${EXTENSION_NAME} version ${VERSION_AVAILABLE} has been installed in ${INSTALL_MODE} mode (Id ${EXTENSION_ID}, Uuid ${EXTENSION_UUID})"
+		echo "Restart Gnome Shell ${CURRENT_VERSION} to take effect."
 
-# else, it is remove mode
-else
+	# else, error
+	else
+		# generate list of available versions
+		LST_VERSION=$(cat ${TMP_VERSION} | sort -V | xargs)
+		
+		# display error message
+		echo "[Error] Gnome Shell version is ${CURRENT_VERSION}, no candidate extension ${EXTENSION_NAME} found"
+		echo "Available versions are ${LST_VERSION}"
+	fi
 
-    # remove extension folder
-    ${INSTALL_SUDO} rm -f -r "${EXTENSION_PATH}/${EXTENSION_UUID}"
+# else, if it is remove mode
+elif [ "${ACTION}" = "remove" ]
+then
 
-    # success message
-    echo "Extension ${EXTENSION_NAME} has been removed in ${INSTALL_MODE} mode (Id ${EXTENSION_ID}, Uuid ${EXTENSION_UUID})"
-    echo "Restart Gnome Shell to take effect."
+	# if extension is installed, removal
+	if [ -d "${EXTENSION_PATH}/${EXTENSION_UUID}" ]
+	then
+		# remove extension folder
+		${INSTALL_SUDO} rm -f -r "${EXTENSION_PATH}/${EXTENSION_UUID}"
+
+		# success message
+		echo "[Success] Extension ${EXTENSION_NAME} has been removed in ${INSTALL_MODE} mode (Id ${EXTENSION_ID}, Uuid ${EXTENSION_UUID})"
+		echo "Restart Gnome Shell ${CURRENT_VERSION} to take effect."
+
+	# else, extension not found, error
+	else
+		# error message
+		echo "[Error] Extension ${EXTENSION_NAME} has not been found in ${INSTALL_MODE} mode (Id ${EXTENSION_ID}, Uuid ${EXTENSION_UUID})"
+	fi
 
 fi
 
